"use client";

import { useState, useEffect } from "react";
import Link from "next/link";

// ── Types ─────────────────────────────────────────────────────────────────────
type Section = {
  id: string;
  title: string;
  content: React.ReactNode;
};

// ── Data ──────────────────────────────────────────────────────────────────────
const SECTIONS: Section[] = [
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    content: (
      <>
        <p>
          By accessing or using the Elibiliby website and student funding
          eligibility checker (the &ldquo;Service&rdquo;), you agree to be bound
          by these Terms and Conditions (&ldquo;Terms&rdquo;). If you do not
          agree with any part of these Terms, you must not use our Service.
        </p>
        <p>
          These Terms apply to all visitors, users, and others who access or use
          the Service. We reserve the right to update or change these Terms at
          any time, and it is your responsibility to check this page
          periodically for changes. Your continued use of the Service following
          any modifications constitutes acceptance of the updated Terms.
        </p>
      </>
    ),
  },
  {
    id: "service-description",
    title: "Description of Service",
    content: (
      <>
        <p>
          Elibiliby provides an online student funding eligibility checker
          designed to give indicative guidance on whether a user may qualify for
          UK student finance. The Service is intended solely as a preliminary
          information tool.
        </p>
        <p>
          <strong>Important:</strong> The eligibility result generated by our
          tool is based on the answers you provide and is indicative only. It
          does not constitute financial advice, legal advice, or a guarantee of
          funding. Eligibility is ultimately determined by Student Finance
          England, Student Finance Wales, or the relevant funding body, based on
          a full assessment of your circumstances.
        </p>
        <p>
          We reserve the right to modify, suspend, or discontinue the Service at
          any time without notice.
        </p>
      </>
    ),
  },
  {
    id: "eligibility-disclaimer",
    title: "Eligibility Checker Disclaimer",
    content: (
      <>
        <p>
          The eligibility checker is provided for general guidance purposes
          only. While we take reasonable care to keep the tool accurate and up
          to date with current Student Finance regulations, we make no
          representations or warranties of any kind, express or implied, about
          the completeness, accuracy, reliability, or suitability of the results
          produced.
        </p>
        <ul>
          <li>
            Results are based solely on the answers you input; inaccurate or
            incomplete responses may lead to an incorrect result.
          </li>
          <li>
            Funding regulations change frequently; always verify your
            eligibility directly with the relevant student finance authority.
          </li>
          <li>
            An &ldquo;Eligible&rdquo; result does not guarantee that a funding
            application will be approved.
          </li>
          <li>
            A &ldquo;Not Eligible&rdquo; result does not definitively mean you
            cannot apply — individual circumstances vary.
          </li>
        </ul>
        <p>
          We strongly recommend consulting a qualified education finance advisor
          or contacting your institution&rsquo;s student services team before
          making any decisions based on our tool.
        </p>
      </>
    ),
  },
  {
    id: "user-obligations",
    title: "User Obligations",
    content: (
      <>
        <p>By using the Service, you agree to:</p>
        <ul>
          <li>
            Provide accurate, current, and complete information when answering
            quiz questions and submitting your contact details.
          </li>
          <li>Not use the Service for any unlawful or prohibited purpose.</li>
          <li>
            Not attempt to gain unauthorised access to any part of the Service
            or its related systems.
          </li>
          <li>
            Not reproduce, duplicate, copy, sell, or exploit any part of the
            Service without express written permission from Elibiliby.
          </li>
          <li>
            Not transmit any unsolicited or unauthorised advertising, spam, or
            promotional material.
          </li>
          <li>
            Not interfere with or disrupt the integrity or performance of the
            Service.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    content: (
      <>
        <p>
          The Service and its original content, features, and functionality are
          and will remain the exclusive property of Eligibility checker. All
          trademarks, service marks, logos, and trade names displayed on the
          Service are proprietary to Elibiliby or their respective owners.
        </p>
        <p>
          You may not reproduce, distribute, modify, create derivative works of,
          publicly display, or commercially exploit any content from the Service
          without our prior written consent.
        </p>
      </>
    ),
  },
  {
    id: "limitation-of-liability",
    title: "Limitation of Liability",
    content: (
      <>
        <p>
          To the fullest extent permitted by applicable law, Elibiliby and its
          directors, employees, and agents shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages, including but
          not limited to:
        </p>
        <ul>
          <li>
            Loss of profits, revenue, data, goodwill, or other intangible
            losses.
          </li>
          <li>
            Reliance on the eligibility checker result as the sole basis for a
            financial or educational decision.
          </li>
          <li>
            Any inaccuracies or errors in the tool resulting from regulatory
            changes.
          </li>
          <li>Unauthorised access to or alteration of your data.</li>
          <li>
            Any bugs, viruses, or other harmful code transmitted through the
            Service.
          </li>
        </ul>
        <p>
          Our total liability to you for any claim arising out of or in
          connection with these Terms or the Service shall not exceed{" "}
          <strong>£100</strong> or the amount paid by you to us in the preceding
          12 months, whichever is greater.
        </p>
      </>
    ),
  },
  {
    id: "third-party-links",
    title: "Third-Party Links & Services",
    content: (
      <>
        <p>
          Our Service may contain links to third-party websites or services that
          are not owned or controlled by Eligiblity checker. We have no control
          over, and assume no responsibility for, the content, privacy policies,
          or practices of any third-party sites or services.
        </p>
        <p>
          We use the following third-party services to power our platform:
          EmailJS (email delivery), Zoho CRM (lead management), and Vercel
          (hosting). By using our Service, you acknowledge that your data may be
          processed by these providers in accordance with their respective
          privacy policies.
        </p>
      </>
    ),
  },
  {
    id: "privacy",
    title: "Privacy",
    content: (
      <>
        <p>
          Your use of the Service is also governed by our{" "}
          <Link
            href="/privacy-policy"
            style={{
              color: "#0a0a0a",
              fontWeight: 700,
              textDecoration: "underline",
            }}
          >
            Privacy Policy
          </Link>
          , which is incorporated into these Terms by reference. By using the
          Service, you consent to the collection and use of your information as
          described in our Privacy Policy.
        </p>
      </>
    ),
  },
  {
    id: "termination",
    title: "Termination",
    content: (
      <>
        <p>
          We reserve the right to terminate or suspend your access to the
          Service immediately, without prior notice or liability, for any
          reason, including if you breach these Terms.
        </p>
        <p>
          Upon termination, your right to use the Service will immediately
          cease. All provisions of these Terms which by their nature should
          survive termination — including intellectual property, disclaimer,
          limitation of liability, and governing law — shall survive.
        </p>
      </>
    ),
  },
  {
    id: "governing-law",
    title: "Governing Law",
    content: (
      <>
        <p>
          These Terms shall be governed by and construed in accordance with the
          laws of England and Wales, without regard to its conflict of law
          provisions.
        </p>
        <p>
          Any disputes arising under or in connection with these Terms shall be
          subject to the exclusive jurisdiction of the courts of England and
          Wales. You waive any objection to the laying of venue of any such
          proceedings in England and Wales.
        </p>
      </>
    ),
  },
  {
    id: "contact",
    title: "Contact Us",
    content: (
      <>
        <p>
          If you have any questions about these Terms and Conditions, please
          contact us:
        </p>
        <div
          style={{
            background: "#fafafa",
            border: "1.5px solid #ebebeb",
            borderRadius: "16px",
            padding: "24px 28px",
            marginTop: "8px",
          }}
        >
          <p
            style={{
              margin: 0,
              fontWeight: 700,
              color: "#0a0a0a",
              fontSize: "16px",
            }}
          >
            Elibiliby
          </p>
          <p style={{ margin: "8px 0 0", color: "#555" }}>
            Email:{" "}
            <a
              href="mailto:rishihranaliexpress@gmail.com"
              style={{
                color: "#0a0a0a",
                fontWeight: 700,
                textDecoration: "underline",
              }}
            >
              info@elibility.com
            </a>
          </p>
        </div>
      </>
    ),
  },
];

// ── Component ─────────────────────────────────────────────────────────────────
export default function TermsAndConditionsPage() {
  const [activeSection, setActiveSection] = useState<string>("acceptance");
  const [tocOpen, setTocOpen] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        });
      },
      { rootMargin: "-20% 0px -70% 0px" },
    );
    SECTIONS.forEach((s) => {
      const el = document.getElementById(s.id);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, []);

  function scrollTo(id: string) {
    const el = document.getElementById(id);
    if (el) {
      el.scrollIntoView({ behavior: "smooth", block: "start" });
      setTocOpen(false);
    }
  }

  const activeTitle = SECTIONS.find((s) => s.id === activeSection)?.title ?? "";

  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#fff",
        fontFamily: "var(--font-plus-jakarta), 'Plus Jakarta Sans', sans-serif",
        color: "#0a0a0a",
      }}
    >
      {/* ── Hero ── */}
      <div
        style={{
          background: "#0a0a0a",
          paddingTop: "clamp(100px, 15vw, 140px)",
          paddingBottom: "clamp(36px, 7vw, 64px)",
          paddingLeft: "clamp(20px, 5vw, 40px)",
          paddingRight: "clamp(20px, 5vw, 40px)",
          position: "relative",
          overflow: "hidden",
        }}
      >
        {/* decorative accent top-right */}
        <div
          style={{
            position: "absolute",
            top: -100,
            right: -100,
            width: "400px",
            height: "400px",
            background: "#D6FD70",
            borderRadius: "50%",
            opacity: 0.05,
            pointerEvents: "none",
          }}
        />
        {/* decorative accent bottom-left */}
        <div
          style={{
            position: "absolute",
            bottom: -60,
            left: -60,
            width: "240px",
            height: "240px",
            background: "#D6FD70",
            borderRadius: "50%",
            opacity: 0.04,
            pointerEvents: "none",
          }}
        />
        <div style={{ maxWidth: "900px", margin: "0 auto", position: "relative" }}>
          <div
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "8px",
              background: "rgba(214,253,112,0.12)",
              border: "1px solid rgba(214,253,112,0.25)",
              borderRadius: "100px",
              padding: "6px 16px",
              marginBottom: "20px",
            }}
          >
            <div
              style={{
                width: "6px",
                height: "6px",
                background: "#D6FD70",
                borderRadius: "50%",
              }}
            />
            <span
              style={{
                color: "#D6FD70",
                fontSize: "12px",
                fontWeight: 700,
                letterSpacing: "0.08em",
                textTransform: "uppercase",
              }}
            >
              Legal
            </span>
          </div>
          <h1
            style={{
              fontSize: "clamp(32px, 7vw, 60px)",
              fontWeight: 900,
              color: "#fff",
              lineHeight: 1.06,
              letterSpacing: "-1.5px",
              margin: "0 0 16px",
            }}
          >
            Terms &amp; Conditions
          </h1>
          <p
            style={{
              fontSize: "clamp(14px, 3.5vw, 17px)",
              color: "rgba(255,255,255,0.5)",
              maxWidth: "560px",
              lineHeight: 1.6,
              margin: 0,
            }}
          >
            Please read these terms carefully before using our student funding
            eligibility checker. Using our service means you agree to these
            terms.
          </p>
          <p
            style={{
              fontSize: "14px",
              color: "rgba(255,255,255,0.3)",
              marginTop: "20px",
              fontWeight: 600,
            }}
          >
            Last updated: 13 May 2026
          </p>
        </div>
      </div>

      {/* ── Important notice banner ── */}
      <div
        style={{
          background: "#D6FD70",
          padding: "16px clamp(20px, 5vw, 40px)",
          display: "flex",
          alignItems: "flex-start",
          gap: "12px",
        }}
      >
        <div
          style={{
            width: "28px",
            height: "28px",
            background: "#0a0a0a",
            borderRadius: "50%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            flexShrink: 0,
            marginTop: "1px",
          }}
        >
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="#D6FD70"
            strokeWidth="2.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <circle cx="12" cy="12" r="10" />
            <line x1="12" y1="8" x2="12" y2="12" />
            <line x1="12" y1="16" x2="12.01" y2="16" />
          </svg>
        </div>
        <p
          style={{
            fontSize: "clamp(13px, 3vw, 14px)",
            fontWeight: 600,
            color: "#0a0a0a",
            margin: 0,
            lineHeight: 1.5,
          }}
        >
          <strong>Important notice:</strong> Our eligibility checker provides
          indicative guidance only and does not constitute financial or legal
          advice. Always verify your eligibility directly with the relevant
          student finance authority.
        </p>
      </div>

      {/* ── Mobile TOC Accordion ── */}
      <div className="mobile-toc">
        <button
          onClick={() => setTocOpen((v) => !v)}
          style={{
            width: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            padding: "16px 20px",
            background: "#fafafa",
            border: "none",
            borderBottom: "1.5px solid #ebebeb",
            cursor: "pointer",
            gap: "12px",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
            <span
              style={{
                fontSize: "10px",
                fontWeight: 800,
                letterSpacing: "0.1em",
                textTransform: "uppercase",
                color: "#bbb",
              }}
            >
              Contents
            </span>
            <span
              style={{
                fontSize: "14px",
                fontWeight: 700,
                color: "#0a0a0a",
              }}
            >
              {activeTitle}
            </span>
          </div>
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="#0a0a0a"
            strokeWidth="2.5"
            strokeLinecap="round"
            strokeLinejoin="round"
            style={{
              transform: tocOpen ? "rotate(180deg)" : "rotate(0deg)",
              transition: "transform 0.2s",
              flexShrink: 0,
            }}
          >
            <polyline points="6 9 12 15 18 9" />
          </svg>
        </button>
        {tocOpen && (
          <nav
            style={{
              background: "#fff",
              borderBottom: "1.5px solid #ebebeb",
              padding: "8px 0",
            }}
          >
            {SECTIONS.map((s, i) => {
              const isActive = activeSection === s.id;
              return (
                <button
                  key={s.id}
                  onClick={() => scrollTo(s.id)}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "12px",
                    background: isActive ? "#0a0a0a" : "transparent",
                    border: "none",
                    borderRadius: "0",
                    padding: "11px 20px",
                    cursor: "pointer",
                    textAlign: "left",
                    width: "100%",
                  }}
                >
                  <span
                    style={{
                      fontSize: "10px",
                      fontWeight: 800,
                      color: isActive ? "#D6FD70" : "#ccc",
                      minWidth: "18px",
                    }}
                  >
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span
                    style={{
                      fontSize: "14px",
                      fontWeight: isActive ? 700 : 500,
                      color: isActive ? "#fff" : "#555",
                    }}
                  >
                    {s.title}
                  </span>
                  {isActive && (
                    <div
                      style={{
                        width: "6px",
                        height: "6px",
                        background: "#D6FD70",
                        borderRadius: "50%",
                        marginLeft: "auto",
                        flexShrink: 0,
                      }}
                    />
                  )}
                </button>
              );
            })}
          </nav>
        )}
      </div>

      {/* ── Body: Sidebar + Content ── */}
      <div className="page-body">
        {/* Desktop Sidebar TOC */}
        <aside className="desktop-sidebar" style={{ position: "sticky", top: "88px" }}>
          <p
            style={{
              fontSize: "11px",
              fontWeight: 800,
              letterSpacing: "0.1em",
              textTransform: "uppercase",
              color: "#bbb",
              marginBottom: "16px",
            }}
          >
            Contents
          </p>
          <nav style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
            {SECTIONS.map((s, i) => {
              const isActive = activeSection === s.id;
              return (
                <button
                  key={s.id}
                  onClick={() => scrollTo(s.id)}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "12px",
                    background: isActive ? "#0a0a0a" : "transparent",
                    border: "none",
                    borderRadius: "12px",
                    padding: "10px 14px",
                    cursor: "pointer",
                    textAlign: "left",
                    transition: "background 0.18s",
                    width: "100%",
                  }}
                >
                  <span
                    style={{
                      fontSize: "10px",
                      fontWeight: 800,
                      color: isActive ? "#D6FD70" : "#ccc",
                      minWidth: "18px",
                    }}
                  >
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span
                    style={{
                      fontSize: "14px",
                      fontWeight: isActive ? 700 : 500,
                      color: isActive ? "#fff" : "#555",
                      lineHeight: 1.3,
                    }}
                  >
                    {s.title}
                  </span>
                  {isActive && (
                    <div
                      style={{
                        width: "6px",
                        height: "6px",
                        background: "#D6FD70",
                        borderRadius: "50%",
                        marginLeft: "auto",
                        flexShrink: 0,
                      }}
                    />
                  )}
                </button>
              );
            })}
          </nav>

          {/* Quick links card */}
          <div
            style={{
              marginTop: "32px",
              background: "#fafafa",
              border: "1.5px solid #ebebeb",
              borderRadius: "16px",
              padding: "20px",
            }}
          >
            <p
              style={{
                fontSize: "11px",
                fontWeight: 800,
                letterSpacing: "0.08em",
                textTransform: "uppercase",
                color: "#bbb",
                margin: "0 0 12px",
              }}
            >
              Also See
            </p>
            <div
              style={{ display: "flex", flexDirection: "column", gap: "8px" }}
            >
              <Link
                href="/privacy-policy"
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                  fontSize: "14px",
                  fontWeight: 600,
                  color: "#0a0a0a",
                  textDecoration: "none",
                }}
              >
                <div
                  style={{
                    width: "6px",
                    height: "6px",
                    background: "#D6FD70",
                    borderRadius: "50%",
                    flexShrink: 0,
                  }}
                />
                Privacy Policy
              </Link>
              <Link
                href="/eligibility-checker"
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                  fontSize: "14px",
                  fontWeight: 600,
                  color: "#0a0a0a",
                  textDecoration: "none",
                }}
              >
                <div
                  style={{
                    width: "6px",
                    height: "6px",
                    background: "#D6FD70",
                    borderRadius: "50%",
                    flexShrink: 0,
                  }}
                />
                Eligibility Checker
              </Link>
            </div>
          </div>
        </aside>

        {/* Main content */}
        <main style={{ minWidth: 0 }}>
          {SECTIONS.map((s, i) => (
            <section
              key={s.id}
              id={s.id}
              style={{
                scrollMarginTop: "96px",
                paddingBottom: "48px",
                borderBottom:
                  i < SECTIONS.length - 1 ? "1.5px solid #f0f0f0" : "none",
                marginBottom: i < SECTIONS.length - 1 ? "48px" : 0,
              }}
            >
              {/* Section header */}
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "14px",
                  marginBottom: "20px",
                }}
              >
                <div
                  style={{
                    width: "36px",
                    height: "36px",
                    background: "#0a0a0a",
                    borderRadius: "10px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    flexShrink: 0,
                  }}
                >
                  <span
                    style={{
                      fontSize: "11px",
                      fontWeight: 800,
                      color: "#D6FD70",
                    }}
                  >
                    {String(i + 1).padStart(2, "0")}
                  </span>
                </div>
                <h2
                  style={{
                    fontSize: "clamp(18px, 4vw, 24px)",
                    fontWeight: 800,
                    color: "#0a0a0a",
                    letterSpacing: "-0.4px",
                    margin: 0,
                  }}
                >
                  {s.title}
                </h2>
              </div>

              {/* Content */}
              <div
                style={{
                  fontSize: "15px",
                  lineHeight: 1.75,
                  color: "#444",
                }}
                className="terms-content"
              >
                {s.content}
              </div>
            </section>
          ))}
        </main>
      </div>

      {/* ── Global styles ── */}
      <style>{`
        /* ── Layout ── */
        .page-body {
          max-width: 1200px;
          margin: 0 auto;
          padding: 60px 40px 100px;
          display: grid;
          grid-template-columns: 260px 1fr;
          gap: 64px;
          align-items: start;
        }
        .mobile-toc {
          display: none;
        }

        /* ── Mobile breakpoint ── */
        @media (max-width: 768px) {
          .desktop-sidebar {
            display: none;
          }
          .mobile-toc {
            display: block;
          }
          .page-body {
            grid-template-columns: 1fr;
            gap: 0;
            padding: 32px 20px 64px;
          }
        }

        /* ── Terms content styles ── */
        .terms-content p {
          margin: 0 0 16px;
          font-size: 15px;
          line-height: 1.75;
          color: #444;
        }
        .terms-content p:last-child {
          margin-bottom: 0;
        }
        .terms-content ul {
          margin: 0 0 16px;
          padding-left: 0;
          list-style: none;
          display: flex;
          flex-direction: column;
          gap: 10px;
        }
        .terms-content ul li {
          display: flex;
          align-items: flex-start;
          gap: 12px;
          font-size: 15px;
          line-height: 1.65;
          color: #444;
        }
        .terms-content ul li::before {
          content: "";
          width: 7px;
          height: 7px;
          background: #D6FD70;
          border-radius: 50%;
          flex-shrink: 0;
          margin-top: 8px;
        }
        .terms-content strong {
          color: #0a0a0a;
          font-weight: 700;
        }
        .terms-content a:hover {
          opacity: 0.75;
        }

        @media (max-width: 480px) {
          .terms-content p,
          .terms-content ul li {
            font-size: 14px;
          }
        }
      `}</style>
    </div>
  );
}